### ISSUE TITLE
第一次登陆时，如果不输入pin码直接登陆，页面上会短暂出现一个"登陆失败"

### ISSUE THREAD

**Issue by jjczh2006** [mudio/bos#13]
第一次登陆时，如果不输入pin码直接登陆，页面上会短暂出现一个"登陆失败"，然后直接登陆进来

**Comment by mudio** [comment]
fix [调整登陆样式](https://github.com/mudio/bos/commit/91223aaa6f6b2726e03025c1cc67a1ff4626e654)
