### ISSUE TITLE
建议图片可以显示缩略图以及直接点击查看

### ISSUE THREAD

**Issue by dovewi** [mudio/bos#36]
图片显示个图片的图标，不够直观。希望可以直接预览
还有贵州移动铁通打不开，我还是挂了vpn才登陆上

**Comment by mudio** [comment]
图片直接展示会收取流量费用，后期可以考虑展示缩略图。近期图片、文档、视频将会支持右键预览。参考 #26 。关于移动铁通打开服务，先确保本地环境可访问`http://bj.bcebos.com`、`http://gz.bcebos.com`，如果有问题请更换DNS。

**Comment by leeight** [comment]
可以添加一个设置的页面，默认关闭，可以自己开启这个功能...
