### ISSUE TITLE
windows纯净版，文件夹下的文件夹多，只显示3个而且无加载更多按钮

### ISSUE THREAD

**Issue by fan0425** [mudio/bos#37]
如题，在一个bucket下有一个文件夹，例如叫data。在data下有很多文件夹，进入到data下只能看到3个文件夹而且没有像web端那样有“加载更多”的按钮，导致data下只能访问这显示出来的3个文件夹。
而且上面的url（如：bj://test-bucket/data），此url是否可以允许用户输入呢？
暂时只发现这两个问题。

**Comment by mudio** [comment]
- data目录如果超过1000个object则滚动到一定位置的时候会自动加载额外的。如果只显示三个那就是bug，我确认下
- 目前还不支持手动输入，但是已经在规划中了。

**Comment by fan0425** [comment]
你说的1000个object是指data目录下所有的文件+文件夹是吗？
我这边确实有这个问题，不会自动加载，或者加个按钮主动点击加载

**Comment by mudio** [comment]
@fan0425 请问你显示的三个目录，目录内文件总和大于1000呢？

**Comment by mudio** [comment]
支持加载更多 https://github.com/mudio/bos/commit/0a03c2087ff30d1880b47c14fd6d28bf43464be1
