### ISSUE TITLE
上传一个大文件使用客户端，总是停止，如图   -- 费元星

### ISSUE THREAD

**Issue by feiyx** [mudio/bos#65]
![image](https://user-images.githubusercontent.com/11736470/29300104-f3ab5bcc-81a5-11e7-8187-fefbee8d7f3f.png)

已经最新的bce客户端 0.3.4

费元星
mail：feiyuanxing@126.com

**Comment by mudio** [comment]
感谢反馈，近期修复此问题~

**Comment by mudio** [comment]
修复，详见`v0.3.5`
