### ISSUE TITLE
上传大文不小心点了暂停 然后永远都在暂停中

### ISSUE THREAD

**Issue by hatvgit** [mudio/bos#67]
* 客户端版本: 0.3.4
* 操作系统版本: win7

**Comment by hatvgit** [comment]
https://github.com/hatvgit/image/blob/master/i.JPG?raw=true

**Comment by mudio** [comment]
不好意思，给您带来使用上的麻烦。

1. 删除任务重新尝试，目前上传在window下有一些非预期的错误
2. 同样可以尝试使用`CLI`进行上传。
3. 近期客户端将会升级，修复此问题
