### ISSUE TITLE
打开软件，重装了N次还是黑屏

### ISSUE THREAD

**Issue by baixiangcpp** [mudio/bos#72]
* 客户端版本:
* 操作系统版本:

### 如何复现
100%必现，需要复现的话，我可以复现。

**Comment by mudio** [comment]
请反馈一下`操作系统版本`与`客户端版本`，以及`黑屏现象`的截图，方便话请粘贴日志
> 日志位置
```shell
%USERPROFILE%\AppData\Roaming\百度云\log.log
```

**Comment by baixiangcpp** [comment]
> %USERPROFILE%\AppData\Roaming\百度云\log.log
下未发现有日志，
 ![image](http://ww4.sinaimg.cn/large/0060lm7Tly1fpeogjhf7kj30h507cq38.jpg)

操作系统版本
 ![image](http://ww3.sinaimg.cn/large/0060lm7Tly1fpeoivlad2j30fa0e2wez.jpg)
黑屏截图
 ![image](http://ww2.sinaimg.cn/large/0060lm7Tly1fpeojqvu1ij307s09gdfl.jpg)

**Comment by mudio** [comment]
> 问题触发环境

- 系统环境：`Win10 16299` 
- 显卡配置：`NAVDIA 独立显卡`

> 参考Issue

- [ ] electron/electron#4380
- [ ] electron/electron#10863

> 目前临时解决方法未验证

- 临时禁用GPU：在快捷方式运行参数`--disable-gpu`

```shell
%USERPROFILE%\AppData\Local\Programs\bce-client\百度云.exe --disable-gpu
```
- 设置程序兼容性
```
右击快捷方式 -> 属性 -> 兼容性 -> 勾选以兼容模式运行此程序
```

**Comment by baixiangcpp** [comment]
OK 确实是这样谢谢！
