### ISSUE TITLE
等待中文件暂停后无法开始任务

### ISSUE THREAD

**Issue by helianthuswhite** [mudio/bos#74]
* 客户端版本: 0.3.10
* 操作系统版本: macos

### 预期行为
同时上传多个文件，文件超过3个时只会开始第一个任务，其他任务为等待状态。将第一个任务暂停之后自动开始下一个任务。
### 当前行为
暂停第一个任务之后后续任务无法自动开始，并且同时开启多个任务，多个任务都会变成等待中，此时暂停/开始按钮已无法再开始任务，所有任务都一直在等待中。
### 如何复现
![image](https://user-images.githubusercontent.com/12878076/38923547-67b18584-432d-11e8-8921-d5705a59a4e0.png)

**Comment by mudio** [comment]
fix mudio/bce-service-bos-transport@004568f88d9186ee436f9e9997f42be10ecb1330
