### ISSUE TITLE
安装后打开客户端菜单栏闪了一下，然后就是显示空白窗口，什么也没有了

### ISSUE THREAD

**Issue by bear01** [mudio/bos#91]
* 客户端版本: 0.46
* 操作系统版本:macOS 11.3.1

### 如何复现
![image](https://user-images.githubusercontent.com/19423627/131990968-888df649-a78e-48e7-a13b-1e4a45a76fdb.png)

**Comment by mudio** [comment]
抱歉，本仓库不再维护，请提交ISSUE到：https://github.com/baidubce/bce-client/issues
